package com.oneplus.android.context;

public interface IOneplusContext {

    public enum EType {
        ONEPLUS_PERMISSION_CONTROL_MANAGER,
        ONEPLUS_PERMISSION,
        ONEPLUS_EXTPROCESSCPUTRACKER,
        ONEPLUS_OPSERVICE,
        ONEPLUS_EXSERVICEMANAGER,
        ONEPLUS_DEVICE_MANAGER,
        ONEPLUS_WALLPAPER_HELPER,
        ONEPLUS_COLORDISPLAY_MANAGER,
        ONEPLUS_NFC_MANAGER,
        ONEPLUS_WIFI_MANAGER,
        ONEPLUS_OIMC_MANAGER,
        ONEPLUS_OPPARALLELAPP,
        ONEPLUS_SCREEN_COMPAT_VIEW,
        ONEPLUS_RINGTONE_MANAGER,
        ONEPLUS_SCREENMODE_MANAGER,
        ONEPLUS_TELEPHONYPERMISSIONS,
        ONEPLUS_ANIMATION,
        ONEPLUS_POWERCONTROLLER,
        ONEPLUS_BATTERYSTATS,
        ONEPLUS_REDSCREEN_ASSERTION,
        ONEPLUS_ICONPACK,
        ONEPLUS_SCENE_CALL_BLOCK,
        ONEPLUS_LONGSCREENSHOT,
        ONEPLUS_FORCE_DARK_MANAGER,
        ONEPLUS_VIEW_ROOT_IMPL,
        ONEPLUS_OPDIAGNOSEUTILS,
        ONEPLUS_IRIS_SERVICE,
        ONEPLUS_BLUETOOTH_MANAGER,
        ONEPLUS_CONNECTIVITY_UTILS,
        ONEPLUS_DYNAMIC_FONT_HELPER,
        ONEPLUS_COTA_CONFIG,
        OPLUS_VRR_MANAGER
    }

    Object queryInterface(EType eType);
}
